apiVersion: skaffold/v1beta13
kind: Config
build:
  local:
    useDockerCLI: true
  tagPolicy:
    gitCommit: {}
  artifacts:
    - image: ippendigital/kafka_zookeeper_exporter
profiles:
  - name: dev
    deploy:
      kubectl:
        manifests:
          - k8s/deployment.yml
          - k8s/config.yml
        flags:
          global:
            - "--namespace=graph"
  - name: prod
    deploy:
      kubectl:
        manifests:
          - k8s/deployment.yml
          - k8s/config-prd.yml
        flags:
          global:
            - "--namespace=graph"